name: Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  quality:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      #- name: Install dependencies
        #run: |
          #go mod download

      - name: Run Unit tests
        run: |
          go test -race -covermode atomic -coverprofile=profile.cov ./...

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
